### ISSUE TITLE
undefined variable 'I' at line 135

### ISSUE THREAD

**Issue by csylvain** [AB4EJ-1/FlexRadioIQ#1]
https://github.com/AB4EJ-1/FlexRadioIQ/blob/a37087b17204064a1ec76c4ffc7d54e24b4aa9bc/flexIQdata2.c#L135

i stared at this line for some time as was unable to discern what exactly is supposed to happen. the buffer is supposed to be interleaved I+Q samples? or all the I samples in the first half of the buffer, and then (in order) all the Q samples in the other half?

**Comment by AB4EJ-1** [comment]
The Flex IQ buffer is composed of 512 IQ samples *.

The FFT_in array is declared as follows:

static fftwf_complex FFT_in[FFT_N];

When you assign a value to this, you do it by giving the real part plus the imaginary part; the imaginary part is designated by multiplying it by I.

FFT_in[bufcount] = iqbuffer.flexDatSample[i].I_val + ( iqbuffer.flexDatSample[i].Q_val * I);

Note that I is not declared anywhere; it is not actually a variable but serves to mark the imaginary part of the complex number.

You can understand the layout of the Flex buffer by looking at the declarations of flexDataBuf and flexDataSample:

struct flexDataSample

{

float I_val;

float Q_val;
};

typedef struct flexDataBuf

{

char VITA_hdr1[2]; // rightmost 4 bits is a packet counter

int16_t VITA_packetsize;

char stream_ID[4];

char class_ID[8];

uint32_t time_stamp;

uint64_t fractional_seconds;

struct flexDataSample flexDatSample[512];
} FLEXBUF;

For a detailed explanation, including actual buffer samples, see page 3 of the TAPR newsletter here: https://files.tapr.org/psr/psr148.pdf for my article "Processing I/Q Data from a FlexRadio into Gnuradio".

Don't hesitate to contact me with further questions. -73-regards- Bill, AB4EJ


* (more precisely QI samples in the case of the Flex, since the imaginary part Q comes first in the pair; this is just a convention, and if you get it reversed the only consequence is that your frequency bins will run from high to low rather than low to high).


From: CSylvain ***@***.***>
Sent: Monday, March 28, 2022 10:37 AM
To: AB4EJ-1/FlexRadioIQ ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [AB4EJ-1/FlexRadioIQ] undefined variable 'I' at line 135 (Issue #1)


https://github.com/AB4EJ-1/FlexRadioIQ/blob/a37087b17204064a1ec76c4ffc7d54e24b4aa9bc/flexIQdata2.c#L135<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAB4EJ-1%2FFlexRadioIQ%2Fblob%2Fa37087b17204064a1ec76c4ffc7d54e24b4aa9bc%2FflexIQdata2.c%23L135&data=04%7C01%7Cbill.engelke%40ua.edu%7C39a4520575be4c2f75de08da10d0d4d5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637840786350236495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o7b2mbquxm%2FM32DdVzacrLVaM1DSMFSM2IflDilEr68%3D&reserved=0>

i stared at this line for some time as was unable to discern what exactly is supposed to happen. the buffer is supposed to be interleaved I+Q samples? or all the I samples in the first half of the buffer, and then (in order) all the Q samples in the other half?

-

**Comment by csylvain** [comment]
thanks for your response!

i follow the datatypes and declarations just fine, and your lengthy response is appreciated.

narrowing the focus on just the questions posed, i will reinterpret the response:
1. yes, the incoming samples are I-Q interleaved/alternating.
2. no, the fftw buffer is not partitioned into I and Q sample blocks.
3. the 'I' identifier is _compiler magic_ introduced by **C99 std** to compose a complex value: `x1 + (x2 * I)` equivalent to _x + iy_ mathematical notation.
